# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: khalilthiero.rssfetcher::lang.item.item

# Model Form Field configuration
form: $/khalilthiero/rssfetcher/models/item/fields.yaml

# Model Class name
modelClass: Khalilthiero\RssFetcher\Models\Item

# Default redirect location
defaultRedirect: khalilthiero/rssfetcher/items

# Create page
create:
    title: khalilthiero.rssfetcher::lang.item.create_item
    redirect: khalilthiero/rssfetcher/items/update/:id
    redirectClose: khalilthiero/rssfetcher/items

# Update page
update:
    title: khalilthiero.rssfetcher::lang.item.edit_item
    redirect: khalilthiero/rssfetcher/items
    redirectClose: khalilthiero/rssfetcher/items
