# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: khalilthiero.rssfetcher::lang.feed.feed

# Model Form Field configuration
form: $/khalilthiero/rssfetcher/models/feed/fields.yaml

# Model Class name
modelClass: Khalilthiero\RssFetcher\Models\Feed

# Default redirect location
defaultRedirect: khalilthiero/rssfetcher/feeds

# Create page
create:
    title: khalilthiero.rssfetcher::lang.feed.create_feed
    redirect: khalilthiero/rssfetcher/feeds/update/:id
    redirectClose: khalilthiero/rssfetcher/feeds

# Update page
update:
    title: khalilthiero.rssfetcher::lang.feed.edit_feed
    redirect: khalilthiero/rssfetcher/feeds
    redirectClose: khalilthiero/rssfetcher/feeds
