# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: khalilthiero.rssfetcher::lang.source.source

# Model Form Field configuration
form: $/khalilthiero/rssfetcher/models/source/fields.yaml

# Model Class name
modelClass: Khalilthiero\RssFetcher\Models\Source

# Default redirect location
defaultRedirect: khalilthiero/rssfetcher/sources

# Create page
create:
    title: khalilthiero.rssfetcher::lang.source.create_source
    redirect: khalilthiero/rssfetcher/sources/update/:id
    redirectClose: khalilthiero/rssfetcher/sources

# Update page
update:
    title: khalilthiero.rssfetcher::lang.source.edit_source
    redirect: khalilthiero/rssfetcher/sources
    redirectClose: khalilthiero/rssfetcher/sources
