# ===================================
#  Import/Export Behavior Config
# ===================================

import:
    title: khalilthiero.rssfetcher::lang.source.import_sources
    modelClass: Khalilthiero\RssFetcher\Models\SourceImport
    list: $/khalilthiero/rssfetcher/models/sourceimport/columns.yaml
    redirect: khalilthiero/rssfetcher/sources
export:
    title: khalilthiero.rssfetcher::lang.source.export_sources
    modelClass: Khalilthiero\RssFetcher\Models\SourceExport
    list: $/khalilthiero/rssfetcher/models/sourceexport/columns.yaml
    redirect: khalilthiero/rssfetcher/sources
    permissions: khalilthiero.rssfetcher.access_import_export
    filename: sources.csv